### ISSUE TITLE
Make the website PWA

### ISSUE THREAD

**Issue by dvmnl** [UncaughtTypeError/Browser-Default-Styles#2]
Maybe it is possible to make the site PWA  like https://dev.to/

**Comment by UncaughtTypeError** [comment]
Definitely possible, and might just do that. Thanks for the suggestion, John.

**Comment by dvmnl** [comment]
I can try to do that

**Comment by UncaughtTypeError** [comment]
A PWA enhancement has been integrated, a service worker is registered with runtime caching.
A web app install prompt is yet to be added though.

Feel free to for fork the repo and enhance it further.
