### ISSUE TITLE
What is your source?

### ISSUE THREAD

**Issue by superole** [UncaughtTypeError/Browser-Default-Styles#4]
Where did you get these defaults? they seem to be somewhat outdated...

**Comment by UncaughtTypeError** [comment]
All sources are listed on the website.

I welcome any correction or updates however as this web application is intended to be evergreen and open sourced, so please feel free to fork the repo and create a pull request.

**Comment by superole** [comment]
It seems that your source, for chromium at least, is not the one used in chromium browsers. But I do not know where the correct source is. Specifically I see that the selector _:focus_ does not have the same rules as reported in the browser.
