### ISSUE TITLE
Provide anchors for direct linking

### ISSUE THREAD

**Issue by ffoodd** [UncaughtTypeError/Browser-Default-Styles#5]
This website would be much more helpful if it allowed to direct link to an element's section (something like `https://browserdefaultstyles.com/#ul`) ala Can I Use.

I often refer to BrowserDefaultStyles, this project is already extremeley helpful so thanks <3

**Comment by UncaughtTypeError** [comment]
That's a great idea. This would be an interesting and useful feature to introduce.

Feel free to fork and create a pull request if you'd like to take a stab at this too.

**Comment by UncaughtTypeError** [comment]
Browser Default Styles now has url hash querying!

Valid fragment identifiers will now match and return results.

Give it a try.
