### ISSUE TITLE
Change pointed for pointer

### ISSUE THREAD

**Issue by emmanuelclement** [UncaughtTypeError/Browser-Default-Styles#8]
https://github.com/UncaughtTypeError/Browser-Default-Styles/blob/f0d92ad72105aecaa162efdc63bd1eca39f9c1d5/scripts/css-defaults.js#L920

Typo on « cursor: pointed ». Correct value is « pointer ».

**Comment by UncaughtTypeError** [comment]
Thanks for _pointing_ that out ;)

Issue resolved ([commit](https://github.com/UncaughtTypeError/Browser-Default-Styles/commit/b69aac8d776cd41531339508a2329b72c8a46fad)).
